yarnPath: .yarn/releases/yarn-3.2.1.cjs
nodeLinker: node-modules
npmPublishRegistry: https://npm.pkg.github.com/
npmPublishAccess: public
npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_AUTH-''}